<ips:template parameters="$table"/>
<ol class='ipsDataList'>
    {{if count($rows)}}
    {{foreach $rows as $row}}
    <li class="ipsDataItem {{if $row->unread()}}ipsDataItem_unread{{endif}}">
        <div class='ipsDataItem_icon ipsPos_top ipsType_center'>
            <i class='ipsType_large fa fa-check-circle' data-role="ipsMenu_selectedIcon"></i>
        </div>
        <div class="ipsDataItem_main">
            <h4 class="ipsDataItem_title"><a href='{$row->url()}'>{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}</a></h4>
            <ul class="ipsDataItem_meta ipsList_inline">
                <li class='ipsType_light'>
                    {datetime="$row->date_report_updated"}
                </li>
                {{foreach $row->stats() as $k => $v}}
                <li>
                    <span class='ipsDataItem_stats_number'>{number="$v"}</span>
                    <span class='ipsDataItem_stats_type'>{lang="$k" pluralize="$v"}</span>
                </li>
                {{endforeach}}
            </ul>
        </div>
        <div class='ipsDataItem_generic ipsDataItem_size1 ipsResponsive_hidePhone ipsType_center'>
            {{if $lastComment = $row->comments( 1, 0, 'date', 'desc' )}}
            {template="userPhoto" app="core" group="global" params="$lastComment->author(), 'tiny'"}
            {{else}}
            {template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
            {{endif}}
        </div>
    </li>
    {{endforeach}}
    {{else}}
    <li class='ipsDataItem'>
        <div class='ipsPad ipsType_light ipsType_center ipsType_normal'>testing</div>
    </li>
    {{endif}}
</ol>
