<ips:template parameters="$mtReport, $prevReport, $nextReport, $form" />
{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) )}}
<article class='ipsColumns ipsColumns_collapseTablet ipsClear ipsClearfix'>
    <div class="ipsColumn ipsColumn_fluid">
        <div class="ipsClearfix">
            <div class='ipsColumns ipsColumns_collapsePhone'>
                <div class='ipsColumn ipsColumn_fluid'>
                    <div class='ipsPageHeader'>
                        <h1 class='ipsType_pageTitle ipsType_largeTitle ipsType_break'>{$mtReport->__get( $mtReport::$databaseColumnMap['title'] )} &nbsp;<span class='ipsType_large ipsType_light ipsType_unbold'>#{$mtReport->__get( $mtReport::$databaseColumnMap['id'] )}</span></h1><br>
                        <i class="fa fa-clock-o"></i> {datetime="$mtReport->__get( $mtReport::$databaseColumnMap['date'] )"}<br><br>
                        
                    </div>
                    <div class='ipsBox ipsPad ipsSpacer_top'>

                        <div class='ipsDataItem_generic ipsDataItem_size1 ipsResponsive_hidePhone ipsType_center'>
                            {template="userPhoto" app="core" group="global" params="$member = \IPS\Member::load( $mtReport->__get( $mtReport::$databaseColumnMap['author'] ) ), 'tiny'"}
                            {$member = \IPS\Member::load( $mtReport->__get( $mtReport::$databaseColumnMap['author'] ) )->name}
                            {$mtReport->__get( $mtReport::$databaseColumnMap['ip_address'])}
                        </div>

                    </div>

                    <div class='ipsSpacer_top ipsBox' data-controller='core.front.core.commentFeed' data-baseURL='{$mtReport->url()}' data-feedID='messages-{$mtReport->id}'>
                        <h2 class='ipsType_sectionTitle ipsType_reset'>{lang="support_responses"}</h2>

                        <div class='ipsAreaBackground_light ipsPad'>
                            <div data-role='commentFeed'>

                            </div>

                            <br><br>


                            <div class='ipsBox ipsBox_transparent ipsAreaBackground ipsPad cNexusSupportMessage_replyArea' data-role='replyArea'>
                                <h3 class='ipsType_sectionHead ipsSpacer_bottom'>Respond to this report request</h3>

                            </div>
                            {$form|raw}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <aside class='ipsColumn ipsColumn_veryWide'>
        <div id="elVerificationSidebar">
            <div class='ipsAreaBackground ipsPad_half' id='elmtReportSidebar_toggle'>


            </div>
            <br>
            <div id='elmtReportPanel' class='ipsBox'>
            {template="mtReportPanel" app="multitrucking" group="modcp" params="$mtReport"}
            </div>
        </div>
    </aside>
</article>
<nav class='ipsPager ipsGrid ipsClearFix ipsList_inline'>
    <div class='ipsGrid_span6 ipsPager_prev'>
        {{if $prevReport}}
        <a href="{url="app=core&module=modcp&controller=modcp&tab=mtreports&action=view&id={$prevReport['id']}" seoTemplate="modcp_mtreports"}" title='{lang="previous_report"}'>
        <span class='ipsPager_type'>{lang="previous_report"}</span>
        <span class='ipsPager_title ipsType_break ipsTruncate ipsTruncate_line'>{$prevReport['title']}</span>
        </a>
        {{endif}}
    </div>
    <div class='ipsGrid_span6 ipsType_right ipsPager_next'>
        {{if $nextReport}}
        <a href="{url="app=core&module=modcp&controller=modcp&tab=mtreports&action=view&id={$nextReport['id']}" seoTemplate="modcp_mtreports"}" title='{lang="next_report"}'>
        <span class='ipsPager_type'>{lang="next_report"}</span>
        <span class='ipsPager_title ipsType_break ipsTruncate ipsTruncate_line'>{$nextReport['title']}</span>
        </a>
        {{endif}}
    </div>
</nav>
{{endif}}


